#!/usr/bin/env bash
# Regenerate THIRD_PARTY_NOTICES.md from the modules linked into the binary.
#
# pinboard-checker statically links BSD-3-Clause dependencies (golang.org/x/net,
# x/sys, x/term), and BSD-3 clause 2 attaches conditions to *binary*
# redistribution: the copyright notice and disclaimer must accompany the
# distribution. Shipping only the project's own MIT LICENSE does not satisfy it.
#
# `go list -deps` walks the main package's imports, so test-only modules are
# correctly excluded -- they are not in the shipped binary.
#
# Lives as a script rather than an inline Justfile recipe because the go list
# format string is full of {{...}}, which just would try to interpolate.
set -euo pipefail

cd "$(dirname "$0")/.."

out=THIRD_PARTY_NOTICES.md
module=$(go list -m)

{
  echo "# Third-Party Notices"
  echo
  echo "\`pinboard-checker\` statically links the Go modules below. Their license"
  echo "terms require that these notices accompany binary distributions."
  echo
  echo "Generated by \`just notices\` — do not edit by hand."
} >"$out"

go list -deps -f '{{with .Module}}{{.Path}}	{{.Version}}	{{.Dir}}{{end}}' . |
  sort -u |
  while IFS=$'\t' read -r path version dir; do
    [ -n "${dir:-}" ] || continue
    [ "$path" != "$module" ] || continue
    for f in LICENSE LICENSE.txt LICENSE.md COPYING NOTICE; do
      [ -f "$dir/$f" ] || continue
      # The filename goes in the heading, not a subheading: a module shipping
      # both LICENSE and NOTICE would otherwise emit the same heading twice and
      # trip markdownlint MD024. ```text, not a bare fence, for MD040.
      printf '\n## %s %s — %s\n\n```text\n' "$path" "$version" "$f" >>"$out"
      cat "$dir/$f" >>"$out"
      printf '```\n' >>"$out"
    done
  done

printf 'wrote %s (%s modules)\n' "$out" "$(grep -c '^## ' "$out")"
